fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.1
    logrotate: git://github.com/rodjek/puppet-logrotate.git
    datacat: git://github.com/richardc/puppet-datacat.git
  symlinks:
    warewulf: "#{source_dir}"
